# Generated by Django 2.2.14 on 2022-12-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
        ),
    ]
