# Generated by Django 2.2.14 on 2022-12-16 14:28

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('numero_paginas', models.IntegerField(max_length=11)),
                ('descripcion', models.TextField()),
                ('portada', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('rol', jsonfield.fields.JSONField(default=dict)),
                ('password', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Autor_Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.Autor')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.Libro')),
            ],
        ),
    ]
