# Generated by Django 2.2.14 on 2022-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_autor_libro_libro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
