# Generated by Django 2.2.14 on 2022-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_auto_20221216_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor_libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
