# Generated by Django 2.2.14 on 2022-12-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_auto_20221216_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor_libro',
            name='id_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libros.Autor'),
        ),
        migrations.AlterField(
            model_name='autor_libro',
            name='id_libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Libros.Libro'),
        ),
    ]
