# Generated by Django 2.2.14 on 2022-12-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0006_auto_20221216_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor_libro',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
