# Generated by Django 2.2.14 on 2022-12-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_auto_20221216_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor_Libro',
        ),
    ]
